# Each license has YAML front matter describing the license's properties.
# The available fields are:

- name: title
  description: https://spdx.org/licenses/ で指定されたライセンスのフルネーム
  required: true

- name: spdx-id
  description: https://spdx.org/licenses/ で指定された短い識別子
  required: true

- name: description
  description: 人間が読めるライセンスの説明
  required: true

- name: how
  description: ライセンスを実装する方法に関する手順書
  required: true

- name: conditions
  description: 必要なルールの箇条書きリスト
  required: true

- name: permissions
  description: 許可されたルールの箇条書きリスト
  required: true

- name: limitations
  description: 制限事項の箇条書きリスト
  required: true

- name: using
  description: "新参者がしたがうことができ、`project_name: license_file_url`の形式で[licensee](https://github.com/licensee/licensee)によって検出できる、明確なLICENSEファイルを使用するライセンスを使用している3つの注目すべきプロジェクトのリスト"
  required: true

# Optional fields

- name: featured
  description: ライセンスがメインページに表示されるべきかどうか（デフォルトはfalse）
  required: false

- name: hidden
  description: ライセンスが、[popular](https://opensource.org/licenses)でもなく、強く条件付けられたものから無条件のものまでの[ライセンスのスペクトル](https://choosealicense.com/licenses/)を埋めるものでもないかどうか（デフォルトはtrue）
  required: false

- name: nickname
  description: 適用される場合の慣習的な短い名前（例：GPLv3）
  required: false

- name: note
  description: ライセンスに関する追加情報
  required: false

- name: redirect_from
  description: 古いURLが壊れるのを防ぐために、ライセンスからリダイレクトする相対パス
  required: false

- name: translate
  description: 多言語訳
  required: false
