name: Build and Test

on:
  push:
    branches: [gh-pages]
  pull_request:
    branches: [gh-pages]
  schedule:
    - cron: "00 21 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4
          bundler-cache: true

      - name: Run tests
        run: ./script/cibuild
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
